// Zentrale Vokabeldatenbank für alle Spiele – Lehrbuch Cursus (Neue Ausgabe), Lektionen 1-6.
// Reihenfolge und Bedeutungen folgen den Wortschatzseiten des Lehrbuchs (S. 222-227).
//
// Herkunft der grammatischen Angaben: 140 Einträge stammen aus der Pontes-Fassung
// dieser Plattform (Stammformen, Valenz, Belebtheit dort fachlich gegengelesen); die Bedeutung
// wurde jeweils auf die Cursus-Formulierung umgestellt. 35 Einträge waren dort nicht
// vorhanden und wurden neu angelegt – deren valenz/subjBelebt/belebt sind NOCH NICHT gegengelesen.
//
// perfectLesson/pppLesson/compLesson sind auf die Cursus-Einführungslektionen gesetzt
// (Perfekt L11, PPP L18, Steigerung L27); bei einer Erweiterung über L6 hinaus
// gehören sie pro Wort geprüft (Cursus führt die Perfektbildungen in L11 UND L12 ein).

const globalVocabularyPool = [

    // ==================== LEKTION 1 ====================
    { latin: "silentium", lesson: 1, type: "noun", belebt: "sache", middle: "silentiī n.", gram_clue: "Genitiv: silentiī, n.", gram_class: "o-Deklination", meaning: "die Ruhe, die Stille, das Schweigen" },
    { latin: "esse", lesson: 1, type: "verb", valenz: "intrans", subjBelebt: false, middle: "sum", perfect: "fuī", perfectLesson: 11, gram_clue: "(kein PPP) 1. Pers. Sg.: sum", gram_class: "unregelmäßiges Verb", meaning: "sein" },
    { latin: "asinus", lesson: 1, type: "noun", belebt: "tier", middle: "asinī m.", gram_clue: "Genitiv: asinī, m.", gram_class: "o-Deklination", meaning: "der Esel" },
    { latin: "nōn iam", lesson: 1, type: "adverb", middle: "Phrase", gram_clue: "", gram_class: "", meaning: "nicht mehr" },
    { latin: "clāmāre", lesson: 1, type: "verb", valenz: "intrans", subjBelebt: true, middle: "clāmō", perfect: "clāmāvī", perfectLesson: 11, ppp: "clāmātum", pppLesson: 18, gram_clue: "1. Pers. Sg.: clāmō", gram_class: "a-Konjugation", meaning: "schreien, (laut) rufen" },
    { latin: "etiam", lesson: 1, type: "conjunction", middle: "Konj.", gram_clue: "", gram_class: "", meaning: "auch; sogar" },
    { latin: "tacēre", lesson: 1, type: "verb", valenz: "intrans", subjBelebt: true, middle: "taceō", perfect: "tacuī", perfectLesson: 11, ppp: "tacitum", pppLesson: 18, gram_clue: "(Perfekt ergänzt) 1. Pers. Sg.: taceō", gram_class: "e-Konjugation", meaning: "schweigen, still sein" },
    { latin: "villa", lesson: 1, type: "noun", belebt: "sache", middle: "villae f.", gram_clue: "Genitiv: villae, f.", gram_class: "a-Deklination", meaning: "das (Land-)Haus; das Landgut" },
    { latin: "iacēre", lesson: 1, type: "verb", valenz: "intrans", subjBelebt: false, middle: "iaceō", perfect: "iacuī", perfectLesson: 11, gram_clue: "(kein PPP) (Perfekt ergänzt) 1. Pers. Sg.: iaceō", gram_class: "e-Konjugation", meaning: "(da)liegen" },
    { latin: "porta", lesson: 1, type: "noun", belebt: "sache", middle: "portae f.", gram_clue: "Genitiv: portae, f.", gram_class: "a-Deklination", meaning: "das Tor, die Tür, der Zugang" },
    { latin: "patēre", lesson: 1, type: "verb", valenz: "intrans", subjBelebt: false, middle: "pateō", perfect: "patuī", gram_clue: "(kein PPP) 1. Pers. Sg.: pateō (kein PPP); patet + AcI: es ist offensichtlich, dass ...", gram_class: "e-Konjugation", meaning: "offen stehen; offenkundig sein; sich erstrecken" },
    { latin: "stāre", lesson: 1, type: "verb", valenz: "intrans", subjBelebt: false, middle: "stō", perfect: "stetī", perfectLesson: 11, gram_clue: "1. Pers. Sg.: stō", gram_class: "a-Konjugation", meaning: "(da)stehen" },
    { latin: "et", lesson: 1, type: "conjunction", middle: "Konj.", gram_clue: "", gram_class: "", meaning: "und; auch" },
    { latin: "exspectāre", lesson: 1, type: "verb", valenz: "akk", subjBelebt: true, middle: "exspectō", perfect: "exspectāvī", perfectLesson: 11, ppp: "exspectātum", pppLesson: 18, gram_clue: "1. Pers. Sg.: exspectō", gram_class: "a-Konjugation", meaning: "warten (auf), erwarten" },
    { latin: "sīc", lesson: 1, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "so" },
    { latin: "cōgitāre", lesson: 1, type: "verb", valenz: "intrans", subjBelebt: true, middle: "cōgitō", perfect: "cōgitāvī", perfectLesson: 11, ppp: "cōgitātum", pppLesson: 18, gram_clue: "1. Pers. Sg.: cōgitō", gram_class: "a-Konjugation", meaning: "denken (an); nachdenken (über); (m. Inf.) beabsichtigen" },
    { latin: "ubi?", lesson: 1, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "wo?" },
    { latin: "cūr?", lesson: 1, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "warum?" },
    { latin: "amīca", lesson: 1, type: "noun", belebt: "person", middle: "amīcae f.", gram_clue: "Genitiv: amīcae, f.", gram_class: "a-Deklination", meaning: "die Freundin" },
    { latin: "nōn", lesson: 1, type: "other", middle: "Negation", gram_clue: "", gram_class: "", meaning: "nicht" },
    { latin: "venīre", lesson: 1, type: "verb", valenz: "intrans", subjBelebt: true, middle: "veniō", perfect: "vēnī", perfectLesson: 11, ppp: "ventum", pppLesson: 18, gram_clue: "1. Pers. Sg.: veniō", gram_class: "i-Konjugation", meaning: "kommen" },
    { latin: "properāre", lesson: 1, type: "verb", valenz: "intrans", subjBelebt: true, middle: "properō", perfect: "properāvī", perfectLesson: 11, ppp: "properātum", pppLesson: 18, gram_clue: "1. Pers. Sg.: properō", gram_class: "a-Konjugation", meaning: "eilen; sich beeilen" },
    { latin: "placēre", lesson: 1, type: "verb", valenz: "dat", subjBelebt: false, middle: "placeō", perfect: "placuī", perfectLesson: 11, ppp: "placitum", pppLesson: 18, gram_clue: "1. Pers. Sg.: placeō", gram_class: "e-Konjugation", meaning: "gefallen" },
    { latin: "(nōn) placet", lesson: 1, type: "other", satzbau: false, middle: "Wendung", gram_clue: "unpersönlich: placet", gram_class: "", meaning: "es macht (keinen) Spaß" },
    { latin: "subitō", lesson: 1, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "plötzlich" },
    { latin: "valdē", lesson: 1, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "sehr" },
    { latin: "gaudēre", lesson: 1, type: "verb", valenz: "intrans", subjBelebt: true, middle: "gaudeō", perfect: "gāvīsus sum", perfectLesson: 11, gram_clue: "Semideponens: Präsens aktiv, Perfekt passivisch gebildet (kein PPP)", gram_class: "e-Konjugation", meaning: "sich freuen" },
    { latin: "quid?", lesson: 1, type: "pronoun", middle: "Pronomen", gram_clue: "", gram_class: "", meaning: "was?" },
    { latin: "ecce!", lesson: 1, type: "other", middle: "Ausruf", gram_clue: "+ Nom./Akk.", gram_class: "", meaning: "schau!/schaut!, sieh da!/seht!" },
    { latin: "quis?", lesson: 1, type: "pronoun", middle: "Pronomen", gram_clue: "", gram_class: "", meaning: "wer?" },

    // ==================== LEKTION 2 ====================
    { latin: "tandem", lesson: 2, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "endlich, schließlich" },
    { latin: "sed", lesson: 2, type: "conjunction", middle: "Konj.", gram_clue: "", gram_class: "", meaning: "aber, (je)doch; sondern" },
    { latin: "appārēre", lesson: 2, type: "verb", valenz: "intrans", subjBelebt: false, middle: "appāreō", perfect: "appāruī", gram_clue: "(kein PPP) 1. Pers. Sg.: appāreō", gram_class: "e-Konjugation", meaning: "erscheinen, sich zeigen; offensichtlich sein" },
    { latin: "familia", lesson: 2, type: "noun", belebt: "person", middle: "familiae f.", gram_clue: "Genitiv: familiae, f.", gram_class: "a-Deklination", meaning: "die Familie" },
    { latin: "sōlum", lesson: 2, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "nur" },
    { latin: "mātrōna", lesson: 2, type: "noun", belebt: "person", middle: "mātrōnae f.", gram_clue: "Genitiv: mātrōnae, f.", gram_class: "a-Deklination", meaning: "die (verheiratete) Frau" },
    { latin: "item", lesson: 2, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "ebenfalls" },
    { latin: "servus", lesson: 2, type: "noun", belebt: "person", middle: "servī m.", gram_clue: "Genitiv: servī, m.", gram_class: "o-Deklination", meaning: "der Sklave; der Diener" },
    { latin: "serva", lesson: 2, type: "noun", belebt: "person", middle: "servae f.", gram_clue: "Genitiv: servae, f.", gram_class: "a-Deklination", meaning: "die Sklavin; die Dienerin" },
    { latin: "ibī", lesson: 2, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "dort, da" },
    { latin: "rīdēre", lesson: 2, type: "verb", valenz: ["intrans","akk"], subjBelebt: true, middle: "rīdeō", perfect: "rīsī", perfectLesson: 11, ppp: "rīsum", pppLesson: 18, gram_clue: "1. Pers. Sg.: rīdeō", gram_class: "e-Konjugation", meaning: "lachen" },
    { latin: "citō", lesson: 2, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "schnell" },
    { latin: "appropinquāre", lesson: 2, type: "verb", valenz: "dat", subjBelebt: true, middle: "appropinquō", perfect: "appropinquāvī", perfectLesson: 11, gram_clue: "1. Pers. Sg.: appropinquō", gram_class: "a-Konjugation", meaning: "sich nähern, näher kommen" },
    { latin: "iam", lesson: 2, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "schon, bereits; nunmehr" },
    { latin: "procul", lesson: 2, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "von Weitem; in der Ferne, weit weg" },
    { latin: "salūtāre", lesson: 2, type: "verb", valenz: "akk", subjBelebt: true, middle: "salūtō", perfect: "salūtāvī", perfectLesson: 11, ppp: "salūtātum", pppLesson: 18, gram_clue: "1. Pers. Sg.: salūtō", gram_class: "a-Konjugation", meaning: "(be)grüßen" },
    { latin: "salvē!/salvēte!", lesson: 2, type: "other", middle: "Ausruf", gram_clue: "", gram_class: "", meaning: "sei/seid gegrüßt!, hallo!" },
    { latin: "tum", lesson: 2, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "da; dann, darauf; damals" },
    { latin: "amīcus", lesson: 2, type: "noun", belebt: "person", middle: "amīcī m.", gram_clue: "Genitiv: amīcī, m.", gram_class: "o-Deklination", meaning: "der Freund" },
    { latin: "cessāre", lesson: 2, type: "verb", valenz: "intrans", subjBelebt: true, middle: "cessō", perfect: "cessāvī", perfectLesson: 11, gram_clue: "1. Pers. Sg.: cessō", gram_class: "a-Konjugation", meaning: "zögern; sich Zeit lassen" },
    { latin: "timēre", lesson: 2, type: "verb", valenz: "akk", subjBelebt: true, middle: "timeō", perfect: "timuī", gram_clue: "(kein PPP) 1. Pers. Sg.: timeō (+ Akk.)", gram_class: "e-Konjugation", meaning: "(sich) fürchten, Angst haben (vor)" },
    { latin: "nunc", lesson: 2, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "nun, jetzt" },
    { latin: "apportāre", lesson: 2, type: "verb", valenz: "akk", subjBelebt: true, middle: "apportō", perfect: "apportāvī", perfectLesson: 11, ppp: "apportātum", pppLesson: 18, gram_clue: "1. Pers. Sg.: apportō", gram_class: "a-Konjugation", meaning: "herbeitragen, (mit)bringen" },
    { latin: "certē", lesson: 2, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "sicher, bestimmt" },
    { latin: "dōnum", lesson: 2, type: "noun", belebt: "sache", middle: "dōnī n.", gram_clue: "Genitiv: dōnī, n.", gram_class: "o-Deklination", meaning: "das Geschenk" },
    { latin: "nam", lesson: 2, type: "conjunction", middle: "Konj.", gram_clue: "", gram_class: "", meaning: "denn" },
    { latin: "mālum", lesson: 2, type: "noun", belebt: "sache", middle: "mālī n.", gram_clue: "Genitiv: mālī, n.", gram_class: "o-Deklination", meaning: "der Apfel" },
    { latin: "dēlectāre", lesson: 2, type: "verb", valenz: "akk", subjBelebt: false, middle: "dēlectō", perfect: "dēlectāvī", perfectLesson: 11, ppp: "dēlectātum", pppLesson: 18, gram_clue: "1. Pers. Sg.: dēlectō", gram_class: "a-Konjugation", meaning: "erfreuen, Freude machen" },
    { latin: "equus", lesson: 2, type: "noun", belebt: "tier", middle: "equī m.", gram_clue: "Genitiv: equī, m.", gram_class: "o-Deklination", meaning: "das Pferd" },

    // ==================== LEKTION 3 ====================
    { latin: "intrāre", lesson: 3, type: "verb", valenz: "akk", subjBelebt: true, middle: "intrō", perfect: "intrāvī", perfectLesson: 11, ppp: "intrātum", pppLesson: 18, gram_clue: "1. Pers. Sg.: intrō", gram_class: "a-Konjugation", meaning: "eintreten; betreten" },
    { latin: "statim", lesson: 3, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "sofort, auf der Stelle" },
    { latin: "rogāre", lesson: 3, type: "verb", valenz: "akk", subjBelebt: true, middle: "rogō", perfect: "rogāvī", perfectLesson: 11, ppp: "rogātum", pppLesson: 18, gram_clue: "1. Pers. Sg.: rogō", gram_class: "a-Konjugation", meaning: "fragen; bitten" },
    { latin: "unde?", lesson: 3, type: "adverb", middle: "Adv.", gram_clue: "Frageadverb", gram_class: "", meaning: "woher?" },
    { latin: "respondēre", lesson: 3, type: "verb", valenz: "dat", subjBelebt: true, aci: "sagen", middle: "respondeō", perfect: "respondī", perfectLesson: 11, ppp: "respōnsum", pppLesson: 18, gram_clue: "1. Pers. Sg.: respondeō", gram_class: "e-Konjugation", meaning: "antworten, entgegnen" },
    { latin: "nūntius", lesson: 3, type: "noun", belebt: "person", middle: "nūntiī m.", gram_clue: "Genitiv: nūntiī, m.", gram_class: "o-Deklination", meaning: "der Bote, die Botschaft" },
    { latin: "dēbēre", lesson: 3, type: "verb", valenz: "intrans", subjBelebt: true, middle: "dēbeō", perfect: "dēbuī", perfectLesson: 11, ppp: "dēbitum", pppLesson: 18, gram_clue: "1. Pers. Sg.: dēbeō", gram_class: "e-Konjugation", meaning: "(m. Inf.) müssen; verdanken, schulden" },
    { latin: "ego/mihi/mē", lesson: 3, type: "pronoun", middle: "Pers.-Pron.", gram_clue: "Nom. / Akk.", gram_class: "", meaning: "ich/mir/mich" },
    { latin: "tū/tibi/tē", lesson: 3, type: "pronoun", middle: "Pers.-Pron.", gram_clue: "Nom. / Akk.", gram_class: "", meaning: "du/dir/dich" },
    { latin: "iubēre", lesson: 3, type: "verb", valenz: "akk", subjBelebt: true, aci: "sagen", middle: "iubeō", perfect: "iussī", ppp: "iussum", gram_clue: "1. Pers. Sg.: iubeō", gram_class: "e-Konjugation", meaning: "(jmdn.) befehlen, (jmdn.) beauftragen" },
    { latin: "in", lesson: 3, type: "preposition", middle: "Präp. + Akk.", gram_clue: "Richtungsangabe", gram_class: "", meaning: "in, an, auf, nach; gegen(über)" },
    { latin: "īnsula", lesson: 3, type: "noun", belebt: "sache", middle: "īnsulae f.", gram_clue: "Genitiv: īnsulae, f.", gram_class: "a-Deklination", meaning: "die Insel; der Wohnblock" },
    { latin: "nāvigāre", lesson: 3, type: "verb", valenz: "intrans", subjBelebt: true, middle: "nāvigō", perfect: "nāvigāvī", ppp: "nāvigātum", gram_clue: "1. Pers. Sg.: nāvigō", gram_class: "a-Konjugation", meaning: "segeln; mit dem Schiff fahren" },
    { latin: "audīre", lesson: 3, type: "verb", valenz: "akk", subjBelebt: true, aci: "wahrnehmen", middle: "audiō", perfect: "audīvī", perfectLesson: 11, ppp: "audītum", pppLesson: 18, gram_clue: "1. Pers. Sg.: audiō", gram_class: "i-Konjugation", meaning: "(an-, er-, zu)hören" },
    { latin: "prōvincia", lesson: 3, type: "noun", belebt: "sache", middle: "prōvinciae f.", gram_clue: "Genitiv: prōvinciae, f.", gram_class: "a-Deklination", meaning: "die Provinz" },
    { latin: "administrāre", lesson: 3, type: "verb", valenz: "akk", subjBelebt: true, middle: "administrō", perfect: "administrāvī", ppp: "administrātum", gram_clue: "1. Pers. Sg.: administrō", gram_class: "a-Konjugation", meaning: "verwalten" },
    { latin: "scīre", lesson: 3, type: "verb", valenz: "akk", subjBelebt: true, aci: "sagen", middle: "sciō", perfect: "scīvī", perfectLesson: 11, ppp: "scītum", pppLesson: 18, gram_clue: "1. Pers. Sg.: sciō", gram_class: "i-Konjugation", meaning: "wissen, kennen; können" },
    { latin: "licēre/licet", lesson: 3, type: "verb", valenz: "dat", subjBelebt: false, satzbau: false, middle: "licet", perfect: "licuit", perfectLesson: 11, gram_clue: "unpersönlich gebraucht: licet (m. Dat.)", gram_class: "e-Konjugation", meaning: "es ist möglich; ist erlaubt, (jmd.) darf" },
    { latin: "perīculum", lesson: 3, type: "noun", belebt: "sache", middle: "perīculī n.", gram_clue: "Genitiv: perīculī, n.", gram_class: "o-Deklination", meaning: "die Gefahr" },
    { latin: "amāre", lesson: 3, type: "verb", valenz: "akk", subjBelebt: true, middle: "amō", perfect: "amāvī", perfectLesson: 11, ppp: "amātum", pppLesson: 18, gram_clue: "1. Pers. Sg.: amō", gram_class: "a-Konjugation", meaning: "lieben" },
    { latin: "nihil", lesson: 3, type: "pronoun", middle: "Pronomen", gram_clue: "indeklinabel", gram_class: "", meaning: "nichts" },
    { latin: "vocāre", lesson: 3, type: "verb", valenz: "akk", subjBelebt: true, middle: "vocō", perfect: "vocāvī", perfectLesson: 11, ppp: "vocātum", pppLesson: 18, gram_clue: "1. Pers. Sg.: vocō", gram_class: "a-Konjugation", meaning: "rufen; nennen" },
    { latin: "hūc", lesson: 3, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "hierher" },
    { latin: "pārēre", lesson: 3, type: "verb", valenz: "dat", subjBelebt: true, middle: "pāreō", perfect: "pāruī", perfectLesson: 11, gram_clue: "(kein PPP) (Perfekt ergänzt) 1. Pers. Sg.: pāreō", gram_class: "e-Konjugation", meaning: "gehorchen" },
    { latin: "parāre", lesson: 3, type: "verb", valenz: "akk", subjBelebt: true, middle: "parō", perfect: "parāvī", perfectLesson: 11, ppp: "parātum", pppLesson: 18, gram_clue: "1. Pers. Sg.: parō", gram_class: "a-Konjugation", meaning: "(vor-, zu)bereiten; (m. Inf.) vorhaben" },
    { latin: "hīc", lesson: 3, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "hier" },
    { latin: "lacrima", lesson: 3, type: "noun", belebt: "sache", middle: "lacrimae f.", gram_clue: "Genitiv: lacrimae, f.", gram_class: "a-Deklination", meaning: "die Träne" },
    { latin: "tenēre", lesson: 3, type: "verb", valenz: "akk", subjBelebt: true, middle: "teneō", perfect: "tenuī", perfectLesson: 11, ppp: "tentum", pppLesson: 18, gram_clue: "1. Pers. Sg.: teneō", gram_class: "e-Konjugation", meaning: "(zurück-, fest)halten" },

    // ==================== LEKTION 4 ====================
    { latin: "homō", lesson: 4, type: "noun", belebt: "person", middle: "hominis m.", gram_clue: "Genitiv: hominis, m.", gram_class: "konsonantische Deklination", meaning: "der Mensch; der Mann; Pl. auch die Leute" },
    { latin: "sedēre", lesson: 4, type: "verb", valenz: "intrans", subjBelebt: true, middle: "sedeō", perfect: "sēdī", perfectLesson: 11, ppp: "sessum", pppLesson: 18, gram_clue: "(Perfekt ergänzt) 1. Pers. Sg.: sedeō", gram_class: "e-Konjugation", meaning: "(da)sitzen" },
    { latin: "diū", lesson: 4, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "lange" },
    { latin: "spectāculum", lesson: 4, type: "noun", belebt: "sache", middle: "spectāculī n.", gram_clue: "Genitiv: spectāculī, n.", gram_class: "o-Deklination", meaning: "das Schauspiel; die Veranstaltung; die Vorführung" },
    { latin: "cōnsul", lesson: 4, type: "noun", belebt: "person", middle: "cōnsulis m.", gram_clue: "Genitiv: cōnsulis, m.", gram_class: "konsonantische Deklination", meaning: "der Konsul (höchster röm. Beamter)" },
    { latin: "avus", lesson: 4, type: "noun", belebt: "person", middle: "avī m.", gram_clue: "Genitiv: avī, m.", gram_class: "o-Deklination", meaning: "der Großvater" },
    { latin: "modo", lesson: 4, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "gerade (eben); nur; (ein)mal" },
    { latin: "autem", lesson: 4, type: "conjunction", middle: "Konj.", gram_clue: "nachgestellt", gram_class: "", meaning: "aber, (je)doch" },
    { latin: "vidēre", lesson: 4, type: "verb", valenz: "akk", subjBelebt: true, aci: "wahrnehmen", middle: "videō", perfect: "vīdī", perfectLesson: 11, ppp: "vīsum", pppLesson: 18, gram_clue: "1. Pers. Sg.: videō", gram_class: "e-Konjugation", meaning: "sehen" },
    { latin: "imperātor", lesson: 4, type: "noun", belebt: "person", middle: "imperātōris m.", gram_clue: "Genitiv: imperātōris, m.", gram_class: "konsonantische Deklination", meaning: "der Kaiser; der Feldherr" },
    { latin: "avē!", lesson: 4, type: "other", middle: "Ausruf", gram_clue: "", gram_class: "", meaning: "sei gegrüßt!" },
    { latin: "populus", lesson: 4, type: "noun", belebt: "person", middle: "populī m.", gram_clue: "Genitiv: populī, m.", gram_class: "o-Deklination", meaning: "das Volk; das Publikum" },
    { latin: "verbum", lesson: 4, type: "noun", belebt: "sache", middle: "verbī n.", gram_clue: "Genitiv: verbī, n.", gram_class: "o-Deklination", meaning: "das Wort" },
    { latin: "simulācrum", lesson: 4, type: "noun", belebt: "sache", middle: "simulācrī n.", gram_clue: "Genitiv: simulācrī, n.", gram_class: "o-Deklination", meaning: "das Bild" },
    { latin: "deus", lesson: 4, type: "noun", belebt: "person", middle: "deī m.", gram_clue: "Genitiv: deī, m.", gram_class: "o-Deklination", meaning: "der Gott" },
    { latin: "rēx", lesson: 4, type: "noun", belebt: "person", middle: "rēgis m.", gram_clue: "Genitiv: rēgis, m.", gram_class: "konsonantische Deklination", meaning: "der König" },
    { latin: "rēgīna", lesson: 4, type: "noun", belebt: "person", middle: "rēgīnae f.", gram_clue: "Genitiv: rēgīnae, f.", gram_class: "a-Deklination", meaning: "die Königin" },
    { latin: "dea", lesson: 4, type: "noun", belebt: "person", middle: "deae f.", gram_clue: "Genitiv: deae, f.", gram_class: "a-Deklination", meaning: "die Göttin" },
    { latin: "amor", lesson: 4, type: "noun", belebt: "sache", middle: "amōris m.", gram_clue: "Genitiv: amōris, m.", gram_class: "konsonantische Deklination", meaning: "die Liebe" },
    { latin: "spectāre", lesson: 4, type: "verb", valenz: "akk", subjBelebt: true, middle: "spectō", perfect: "spectāvī", perfectLesson: 11, ppp: "spectātum", pppLesson: 18, gram_clue: "1. Pers. Sg.: spectō", gram_class: "a-Konjugation", meaning: "(an)schauen; betrachten" },
    { latin: "initium", lesson: 4, type: "noun", belebt: "sache", middle: "initiī n.", gram_clue: "Genitiv: initiī, n.", gram_class: "o-Deklination", meaning: "der Anfang, der Beginn" },
    { latin: "signum", lesson: 4, type: "noun", belebt: "sache", middle: "signī n.", gram_clue: "Genitiv: signī, n.", gram_class: "o-Deklination", meaning: "das Zeichen; das Merkmal" },
    { latin: "dare", lesson: 4, type: "verb", valenz: "dat+akk", subjBelebt: true, middle: "dō", perfect: "dedī", perfectLesson: 11, ppp: "datum", pppLesson: 18, gram_clue: "1. Pers. Sg.: dō", gram_class: "a-Konjugation", meaning: "(von sich) geben" },
    { latin: "incitāre", lesson: 4, type: "verb", valenz: "akk", subjBelebt: false, middle: "incitō", perfect: "incitāvī", perfectLesson: 11, ppp: "incitātum", pppLesson: 18, gram_clue: "1. Pers. Sg.: incitō", gram_class: "a-Konjugation", meaning: "antreiben, anfeuern" },
    { latin: "ārdor", lesson: 4, type: "noun", belebt: "sache", middle: "ārdōris m.", gram_clue: "Genitiv: ārdōris, m.", gram_class: "konsonantische Deklination", meaning: "das Temperament; die Begeisterung; die Hitze" },
    { latin: "clāmor", lesson: 4, type: "noun", belebt: "sache", middle: "clāmōris m.", gram_clue: "Genitiv: clāmōris, m.", gram_class: "konsonantische Deklination", meaning: "der Schrei, der Ruf, das Geschrei" },
    { latin: "furor", lesson: 4, type: "noun", belebt: "sache", middle: "furōris m.", gram_clue: "Genitiv: furōris, m.", gram_class: "konsonantische Deklination", meaning: "das Toben; der Wahnsinn; die Raserei" },
    { latin: "neque", lesson: 4, type: "conjunction", middle: "Konj.", gram_clue: "", gram_class: "", meaning: "und ... nicht; auch ... nicht; aber ... nicht" },

    // ==================== LEKTION 5 ====================
    { latin: "ante", lesson: 5, type: "preposition", middle: "Präp. + Akk.", gram_clue: "", gram_class: "", meaning: "vor" },
    { latin: "lūdere", lesson: 5, type: "verb", valenz: "intrans", subjBelebt: true, middle: "lūdō", perfect: "lūsī", perfectLesson: 11, ppp: "lūsum", pppLesson: 18, gram_clue: "(Perfekt ergänzt) 1. Pers. Sg.: lūdō", gram_class: "konsonantische Konjugation", meaning: "spielen" },
    { latin: "semper", lesson: 5, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "immer" },
    { latin: "pater", lesson: 5, type: "noun", belebt: "person", middle: "patris m.", gram_clue: "Genitiv: patris, m.", gram_class: "konsonantische Deklination", meaning: "der Vater" },
    { latin: "patrōnus", lesson: 5, type: "noun", belebt: "person", middle: "patrōnī m.", gram_clue: "Genitiv: patrōnī, m.", gram_class: "o-Deklination", meaning: "der Anwalt, der Verteidiger; der Schirmherr" },
    { latin: "causa", lesson: 5, type: "noun", belebt: "sache", middle: "causae f.", gram_clue: "Genitiv: causae, f.", gram_class: "a-Deklination", meaning: "der Grund; der Prozess, der Streitfall" },
    { latin: "dīcere", lesson: 5, type: "verb", valenz: "akk", subjBelebt: true, aci: "sagen", middle: "dīcō", perfect: "dīxī", perfectLesson: 11, ppp: "dictum", pppLesson: 18, gram_clue: "1. Pers. Sg.: dīcō", gram_class: "konsonantische Konjugation", meaning: "sagen; sprechen; (m. doppeltem Akk.) nennen" },
    { latin: "forum", lesson: 5, type: "noun", belebt: "sache", middle: "forī n.", gram_clue: "Genitiv: forī, n.", gram_class: "o-Deklination", meaning: "das Forum; der Marktplatz" },
    { latin: "dum", lesson: 5, type: "conjunction", middle: "Subj. + Präs.", gram_clue: "", gram_class: "", meaning: "während" },
    { latin: "epistula", lesson: 5, type: "noun", belebt: "sache", middle: "epistulae f.", gram_clue: "Genitiv: epistulae, f.", gram_class: "a-Deklination", meaning: "der Brief" },
    { latin: "legere", lesson: 5, type: "verb", valenz: "akk", subjBelebt: true, middle: "legō", perfect: "lēgī", perfectLesson: 11, ppp: "lēctum", pppLesson: 18, gram_clue: "1. Pers. Sg.: legō", gram_class: "konsonantische Konjugation", meaning: "lesen; sammeln; auswählen" },
    { latin: "nox", lesson: 5, type: "noun", belebt: "sache", middle: "noctis f.", gram_clue: "Genitiv: noctis, f. (Gen. Pl. noctium)", gram_class: "konsonantische Deklination", meaning: "die Nacht" },
    { latin: "iūdex", lesson: 5, type: "noun", belebt: "person", middle: "iūdicis m.", gram_clue: "Genitiv: iūdicis, m.", gram_class: "konsonantische Deklination", meaning: "der Richter" },
    { latin: "dormīre", lesson: 5, type: "verb", valenz: "intrans", subjBelebt: true, middle: "dormiō", perfect: "dormīvī", ppp: "dormītum", gram_clue: "1. Pers. Sg.: dormiō", gram_class: "i-Konjugation", meaning: "schlafen" },
    { latin: "invādere", lesson: 5, type: "verb", valenz: "akk", subjBelebt: true, middle: "invādō", perfect: "invāsī", perfectLesson: 11, ppp: "invāsum", pppLesson: 18, gram_clue: "1. Pers. Sg.: invādō", gram_class: "konsonantische Konjugation", meaning: "eindringen, angreifen" },
    { latin: "domina", lesson: 5, type: "noun", belebt: "person", middle: "dominae f.", gram_clue: "Genitiv: dominae, f.", gram_class: "a-Deklination", meaning: "die (Haus-)Herrin" },
    { latin: "sūmere", lesson: 5, type: "verb", valenz: "akk", subjBelebt: true, middle: "sūmō", perfect: "sūmpsī", perfectLesson: 11, ppp: "sūmptum", pppLesson: 18, gram_clue: "1. Pers. Sg.: sūmō", gram_class: "konsonantische Konjugation", meaning: "nehmen" },
    { latin: "dēcēdere", lesson: 5, type: "verb", valenz: "intrans", subjBelebt: true, middle: "dēcēdō", perfect: "dēcessī", perfectLesson: 11, ppp: "dēcessum", pppLesson: 18, gram_clue: "1. Pers. Sg.: dēcēdō", gram_class: "konsonantische Konjugation", meaning: "weggehen, gehen (aus)" },
    { latin: "accurrere", lesson: 5, type: "verb", valenz: "intrans", subjBelebt: true, middle: "accurrō", perfect: "accurrī", perfectLesson: 12, ppp: "accursum", pppLesson: 18, gram_clue: "1. Pers. Sg.: accurrō (Perfekt auch accucurrī)", gram_class: "konsonantische Konjugation", meaning: "herbeilaufen, angelaufen kommen" },
    { latin: "dominus", lesson: 5, type: "noun", belebt: "person", middle: "dominī m.", gram_clue: "Genitiv: dominī, m.", gram_class: "o-Deklination", meaning: "der (Haus-)Herr" },
    { latin: "fūr", lesson: 5, type: "noun", belebt: "person", middle: "fūris m.", gram_clue: "Genitiv: fūris, m.", gram_class: "konsonantische Deklination", meaning: "der Dieb" },
    { latin: "quaerere", lesson: 5, type: "verb", valenz: "akk", subjBelebt: true, middle: "quaerō", perfect: "quaesīvī", perfectLesson: 11, ppp: "quaesītum", pppLesson: 18, gram_clue: "(Perfekt ergänzt) 1. Pers. Sg.: quaerō", gram_class: "konsonantische Konjugation", meaning: "suchen; fragen" },
    { latin: "reus", lesson: 5, type: "noun", belebt: "person", middle: "reī m.", gram_clue: "Genitiv: reī, m.", gram_class: "o-Deklination", meaning: "der Angeklagte" },
    { latin: "sī", lesson: 5, type: "conjunction", middle: "Subj.", gram_clue: "", gram_class: "", meaning: "wenn, falls" },
    { latin: "fuga", lesson: 5, type: "noun", belebt: "sache", middle: "fugae f.", gram_clue: "Genitiv: fugae, f.", gram_class: "a-Deklination", meaning: "die Flucht" },
    { latin: "petere", lesson: 5, type: "verb", valenz: "akk", subjBelebt: true, middle: "petō", perfect: "petīvī", perfectLesson: 11, ppp: "petītum", pppLesson: 18, gram_clue: "1. Pers. Sg.: petō", gram_class: "konsonantische Konjugation", meaning: "bitten, verlangen; angreifen; aufsuchen; gehen zu/fahren nach" },
    { latin: "fugam petere", lesson: 5, type: "verb", valenz: "intrans", subjBelebt: true, satzbau: false, middle: "fugam petō", perfect: "fugam petīvī", perfectLesson: 11, gram_clue: "feste Wendung; 1. Pers. Sg.: fugam petō", gram_class: "konsonantische Konjugation", meaning: "die Flucht ergreifen" },
    { latin: "solēre", lesson: 5, type: "verb", valenz: "intrans", subjBelebt: true, middle: "soleō", perfect: "solitus sum", perfectLesson: 11, gram_clue: "Semideponens: Präsens aktiv, Perfekt passivisch gebildet (kein PPP); + Inf.", gram_class: "e-Konjugation", meaning: "gewohnt sein, (etw.) normalerweise (tun)" },
    { latin: "ōrātor", lesson: 5, type: "noun", belebt: "person", middle: "ōrātōris m.", gram_clue: "Genitiv: ōrātōris, m.", gram_class: "konsonantische Deklination", meaning: "der Redner" },
    { latin: "plaudere", lesson: 5, type: "verb", valenz: ["intrans","dat"], subjBelebt: true, middle: "plaudō", perfect: "plausī", perfectLesson: 11, ppp: "plausum", pppLesson: 18, gram_clue: "1. Pers. Sg.: plaudō", gram_class: "konsonantische Konjugation", meaning: "Beifall klatschen, applaudieren" },

    // ==================== LEKTION 6 ====================
    { latin: "nāvis", lesson: 6, type: "noun", belebt: "sache", middle: "nāvis f.", gram_clue: "Genitiv: nāvis, f. (Gen. Pl. nāvium)", gram_class: "konsonantische Deklination", meaning: "das Schiff" },
    { latin: "laetus, laeta, laetum", lesson: 6, type: "adjective", middle: "a-/o-Deklination", gram_clue: "Adjektiv (o-/a-)", gram_class: "a-/o-Deklination", meaning: "froh; fröhlich" },
    { latin: "ad", lesson: 6, type: "preposition", middle: "Präp. + Akk.", gram_clue: "", gram_class: "", meaning: "zu; zu ... hin; an; bei" },
    { latin: "terra", lesson: 6, type: "noun", belebt: "sache", middle: "terrae f.", gram_clue: "Genitiv: terrae, f.", gram_class: "a-Deklination", meaning: "die Erde; das Land" },
    { latin: "novus, nova, novum", lesson: 6, type: "adjective", middle: "a-/o-Deklination", gram_clue: "Adjektiv (o-/a-)", gram_class: "a-/o-Deklination", meaning: "neu" },
    { latin: "aliēnus, aliēna, aliēnum", lesson: 6, type: "adjective", middle: "a-/o-Deklination", gram_clue: "Adjektiv (o-/a-)", gram_class: "a-/o-Deklination", meaning: "fremd" },
    { latin: "maestus, maesta, maestum", lesson: 6, type: "adjective", middle: "a-/o-Deklination", gram_clue: "Adjektiv (o-/a-)", gram_class: "a-/o-Deklination", meaning: "traurig" },
    { latin: "ventus", lesson: 6, type: "noun", belebt: "sache", middle: "ventī m.", gram_clue: "Genitiv: ventī, m.", gram_class: "o-Deklination", meaning: "der Wind, der Sturm" },
    { latin: "secundus, secunda, secundum", lesson: 6, type: "adjective", middle: "a-/o-Deklination", gram_clue: "Adjektiv (o-/a-)", gram_class: "a-/o-Deklination", meaning: "der zweite, der folgende; günstig" },
    { latin: "nauta", lesson: 6, type: "noun", belebt: "person", middle: "nautae m.", gram_clue: "Genitiv: nautae, m. (Maskulinum der a-Deklination)", gram_class: "a-Deklination", meaning: "der Seemann" },
    { latin: "sōlus, sōla, sōlum", lesson: 6, type: "adjective", middle: "a-/o-Deklination", gram_clue: "Adjektiv, Pronominal-Dekl. (Gen. sōlīus, Dat. sōlī)", gram_class: "a-/o-Deklination", meaning: "allein, einzig; nur" },
    { latin: "māgnus, māgna, māgnum", lesson: 6, type: "adjective", middle: "a-/o-Deklination", comp: "maior", superl: "maximus", compLesson: 27, gram_clue: "Adjektiv (o-/a-); Komparativ/Superlativ unregelmäßig", gram_class: "a-/o-Deklination", meaning: "groß(artig); bedeutend" },
    { latin: "māter", lesson: 6, type: "noun", belebt: "person", middle: "mātris f.", gram_clue: "Genitiv: mātris, f.", gram_class: "konsonantische Deklination", meaning: "die Mutter" },
    { latin: "pīrāta", lesson: 6, type: "noun", belebt: "person", middle: "pīrātae m.", gram_clue: "Genitiv: pīrātae, m. (maskulin trotz a-Deklination)", gram_class: "a-Deklination", meaning: "der Pirat, der Seeräuber" },
    { latin: "arma", lesson: 6, type: "noun", belebt: "sache", middle: "armōrum n. Pl.", gram_clue: "Genitiv: armōrum, n. (nur Plural)", gram_class: "o-Deklination", meaning: "die Waffen (Pluralwort)" },
    { latin: "abdūcere", lesson: 6, type: "verb", valenz: "akk", subjBelebt: true, middle: "abdūcō", perfect: "abdūxī", ppp: "abductum", gram_clue: "1. Pers. Sg.: abdūcō", gram_class: "konsonantische Konjugation", meaning: "wegführen; (weg)bringen; verschleppen" },
    { latin: "fēmina", lesson: 6, type: "noun", belebt: "person", middle: "fēminae f.", gram_clue: "Genitiv: fēminae, f.", gram_class: "a-Deklination", meaning: "die Frau" },
    { latin: "dēfendere", lesson: 6, type: "verb", valenz: "akk", subjBelebt: true, middle: "dēfendō", perfect: "dēfendī", perfectLesson: 11, ppp: "dēfēnsum", pppLesson: 18, gram_clue: "1. Pers. Sg.: dēfendō", gram_class: "konsonantische Konjugation", meaning: "verteidigen; abwehren" },
    { latin: "ubīque", lesson: 6, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "überall" },
    { latin: "ōrāre", lesson: 6, type: "verb", valenz: "akk", subjBelebt: true, middle: "ōrō", perfect: "ōrāvī", ppp: "ōrātum", gram_clue: "1. Pers. Sg.: ōrō", gram_class: "a-Konjugation", meaning: "(er)bitten; beten" },
    { latin: "bonus, bona, bonum", lesson: 6, type: "adjective", middle: "a-/o-Deklination", comp: "melior", superl: "optimus", compLesson: 27, gram_clue: "Adjektiv (o-/a-); Komparativ/Superlativ unregelmäßig", gram_class: "a-/o-Deklination", meaning: "gut; tüchtig" },
    { latin: "auxilium", lesson: 6, type: "noun", belebt: "sache", middle: "auxiliī n.", gram_clue: "Genitiv: auxiliī, n.", gram_class: "o-Deklination", meaning: "die Hilfe" },
    { latin: "multī, multae, multa", lesson: 6, type: "adjective", middle: "a-/o-Deklination", comp: "plūrēs", superl: "plūrimī", gram_clue: "Adjektiv (Plural); Komparativ/Superlativ unregelmäßig", gram_class: "a-/o-Deklination", meaning: "viele; zahlreiche" },
    { latin: "multum", lesson: 6, type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "viel" },
    { latin: "pūgnāre", lesson: 6, type: "verb", valenz: "intrans", subjBelebt: true, middle: "pūgnō", perfect: "pūgnāvī", perfectLesson: 11, ppp: "pūgnātum", pppLesson: 18, gram_clue: "1. Pers. Sg.: pūgnō", gram_class: "a-Konjugation", meaning: "kämpfen" },
    { latin: "superāre", lesson: 6, type: "verb", valenz: "akk", subjBelebt: true, middle: "superō", perfect: "superāvī", ppp: "superātum", gram_clue: "1. Pers. Sg.: superō", gram_class: "a-Konjugation", meaning: "(be)siegen; übertreffen" },
    { latin: "alius, alia, aliud", lesson: 6, type: "pronoun", middle: "Pronomen", gram_clue: "Gen. alterīus, Dat. aliī", gram_class: "", meaning: "ein anderer" },
    { latin: "aliī ... aliī ...", lesson: 6, type: "conjunction", middle: "Phrase", gram_clue: "", gram_class: "", meaning: "die einen ... (die) andere(n)" },
    { latin: "necāre", lesson: 6, type: "verb", valenz: "akk", subjBelebt: true, middle: "necō", perfect: "necāvī", perfectLesson: 11, ppp: "necātum", pppLesson: 18, gram_clue: "1. Pers. Sg.: necō", gram_class: "a-Konjugation", meaning: "töten" },
    { latin: "praecipitāre", lesson: 6, type: "verb", valenz: ["akk","intrans"], subjBelebt: true, middle: "praecipitō", perfect: "praecipitāvī", perfectLesson: 11, ppp: "praecipitātum", pppLesson: 18, gram_clue: "1. Pers. Sg.: praecipitō", gram_class: "a-Konjugation", meaning: "(jmdn.) hinabstürzen; stoßen; hinabstürzen, (herunter)fallen" }
];
